name: Deploy WordPress on EC2 and Scan with Trivy

on:
  push:
    branches:
      - main

jobs:
  deploy-and-scan:
    name: Deploy WordPress on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull charliebanny/dockerhub:myfirstimagepush

      - name: Install Trivy
        run: |
          curl -sfL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -yq trivy

      - name: Scan Docker Image with Trivy
        run: trivy --severity MEDIUM,HIGH,CRITICAL charliebanny/dockerhub:myfirstimagepush
