name: Deploy WordPress on EC2 and Scan with Trivy

on:
  push:
    branches:
      - main

jobs:
  deploy-and-scan:
    name: Deploy WordPress on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Pull Docker Image
        run: docker pull charliebanny/dockerhub:myfirstimagepush

      # Install Trivy
      - name: Install Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -yq trivy

  build:
    name: Image scan
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scanners: 'vuln'
        scan-ref: 'wordpress:latest'
        hide-progress: false
        format: 'table'
        ignore-unfixed: true
